service: crud-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: 'lambda-dev-recluta'
  region: 'us-east-1'

plugins:
  - serverless-offline


functions:
  servicioGet:
    handler: handlerGet.servicioGet
    events:
      - httpApi:
          path: /message/{message}
          method: get
  servicioPost:
    handler: handlerPost.servicioPOST
    events:
      - httpApi:
          path: /message
          method: post